knife4j:
  enable: true
  openapi:
    title: ${hm.swagger.title}服务接口文档
    description: "${hm.swagger.desc}接口文档"
    email: zhanghuyi@itcast.cn
    concat: 虎哥
    url: https://www.itcast.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - ${hm.swagger.package}